language: python

python:
  - 3.7

if: tag IS present AND type != pull_request

git:
  submodules: false

before_install:
  # cannot use SSH to fetch submodule
  - sed -i 's#git@github.com:#https://github.com/#' .gitmodules
  - git submodule update --init --recursive

install:
  - pip install -r requirements.txt

scripts:
  - qgis-plugin-ci -v
  - qgis-plugin-ci release ${TRAVIS_TAG}
          --github-token ${GH_TOKEN}
          --osgeo-username ${OSGEO_USERNAME}
          --osgeo-password ${OSGEO_PASSWORD}

env:
  global:
    # OSGEO_USERNAME
    # OSGEO_PASSWORD
    # TX_TOKEN
    # GH_TOKEN
